### ISSUE TITLE
Bug in find_from

### ISSUE THREAD

**Issue by olyaromanyuk** [NVIDIA/nvstrings#5]
find_from function works not as expected when passing array as starts parameter. The parameter has effect only on the first string in the string array.
Code sample:

```
>>> import nvstrings
>>> from numba import cuda
>>> s1 = "aaaaaaaaa"
>>> s2 = "aaaaaaaaa"
>>> strings = [s1,s2]
>>> gpu_strings = nvstrings.to_device(strings)
>>> gpu_strings.find('a')
[0, 0]
>>> gpu_strings.find('a', start=5)
[5, 5]
>>> starts = cuda.to_device([5,7])
>>> gpu_strings.find_from('a', starts=starts.device_ctypes_pointer.value)
[5, 0]

```

**Comment by davidwendt** [comment]
The problem is that the `starts` variable here is created as dtype `int64` and the `find_from` is expecting memory for `int32`. There is no dtype parameter on the `cuda.to_device()` method so the best option is to use numpy to create `starts` like in the following:
```
>>> import numpy as np
>>> starts = cuda.to_device(np.asarray([5,5],dtype=np.int32))
>>> starts.dtype
dtype('int32')
>>> gpu_strings.find_from('a',starts=starts.device_ctypes_pointer.value)
[5, 5]
```
I will update the nvstrings.py documentation to make it clear that the `starts` and `ends` parameters are required to be `int32` values.

**Comment by olyaromanyuk** [comment]
Thank you, this fixed my issue
